domain: "ago.ofnir.xyz"
author: "Joane Doe"
email: "joane.doe@ago.ofnir.xyz"
website_name: "an Ago Blog!"
github_account: "dvwallin"
title: "an Ago Blog!"
description: "This is an awesome Ago Blog!"
keywords: "ago,blog,awesome"